// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OCBManager.Data.Data;

#nullable disable

namespace OCBManager.API.Migrations
{
    [DbContext(typeof(OCBContext))]
    [Migration("20221220212607_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OCBManager.Domain.Models.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BillClassId")
                        .HasColumnType("int");

                    b.Property<int>("BillNumber")
                        .HasColumnType("int");

                    b.Property<int>("IncomingBalanceId")
                        .HasColumnType("int");

                    b.Property<int>("OutgoingBalanceId")
                        .HasColumnType("int");

                    b.Property<int>("TurnoverId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BillClassId");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("OCBManager.Domain.Models.BillClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("IncomingBalanceActive")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("IncomingBalancePassive")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OutgoingBalanceActive")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("OutgoingBalancePassive")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TurnoverCredit")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TurnoverDebit")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("TurnoverSheetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TurnoverSheetId");

                    b.ToTable("BillClasses");
                });

            modelBuilder.Entity("OCBManager.Domain.Models.IncomingBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Active")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("BillId")
                        .HasColumnType("int");

                    b.Property<decimal>("Passive")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("BillId")
                        .IsUnique();

                    b.ToTable("IncomingBalances");
                });

            modelBuilder.Entity("OCBManager.Domain.Models.OutgoingBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Active")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("BillId")
                        .HasColumnType("int");

                    b.Property<decimal>("Passive")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("BillId")
                        .IsUnique();

                    b.ToTable("OutgoingBalances");
                });

            modelBuilder.Entity("OCBManager.Domain.Models.Turnover", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BillId")
                        .HasColumnType("int");

                    b.Property<decimal>("Credit")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Debit")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("BillId")
                        .IsUnique();

                    b.ToTable("Turnovers");
                });

            modelBuilder.Entity("OCBManager.Domain.Models.TurnoverSheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("IncomingBalanceActive")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("IncomingBalancePassive")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OutgoingBalanceActive")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("OutgoingBalancePassive")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TurnoverCredit")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TurnoverDebit")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.ToTable("TurnoverSheets");
                });

            modelBuilder.Entity("OCBManager.Domain.Models.Bill", b =>
                {
                    b.HasOne("OCBManager.Domain.Models.BillClass", "BillClass")
                        .WithMany("Bills")
                        .HasForeignKey("BillClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BillClass");
                });

            modelBuilder.Entity("OCBManager.Domain.Models.BillClass", b =>
                {
                    b.HasOne("OCBManager.Domain.Models.TurnoverSheet", "TurnoverSheet")
                        .WithMany()
                        .HasForeignKey("TurnoverSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TurnoverSheet");
                });

            modelBuilder.Entity("OCBManager.Domain.Models.IncomingBalance", b =>
                {
                    b.HasOne("OCBManager.Domain.Models.Bill", "Bill")
                        .WithOne("IncomingBalance")
                        .HasForeignKey("OCBManager.Domain.Models.IncomingBalance", "BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("OCBManager.Domain.Models.OutgoingBalance", b =>
                {
                    b.HasOne("OCBManager.Domain.Models.Bill", "Bill")
                        .WithOne("OutgoingBalance")
                        .HasForeignKey("OCBManager.Domain.Models.OutgoingBalance", "BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("OCBManager.Domain.Models.Turnover", b =>
                {
                    b.HasOne("OCBManager.Domain.Models.Bill", "Bill")
                        .WithOne("Turnover")
                        .HasForeignKey("OCBManager.Domain.Models.Turnover", "BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("OCBManager.Domain.Models.Bill", b =>
                {
                    b.Navigation("IncomingBalance")
                        .IsRequired();

                    b.Navigation("OutgoingBalance")
                        .IsRequired();

                    b.Navigation("Turnover")
                        .IsRequired();
                });

            modelBuilder.Entity("OCBManager.Domain.Models.BillClass", b =>
                {
                    b.Navigation("Bills");
                });
#pragma warning restore 612, 618
        }
    }
}
